### ISSUE TITLE
Manual approve button opens RMP overview

### ISSUE THREAD

**Issue by alex5nader** [nitinankad/utdegree-planner#6]
When clicking manual approve or undo approve, the course is marked as approved or unapproved, but the Rate My Professor dialog also appears. It would be nice if the RMP dialog only appears when not approving courses.

 I'm using Firefox 82.0.2 on Linux, in case this behavior is not universal.

**Comment by nitinankad** [comment]
Yeah I've noticed this issue as well. I've contacted @sunnyguan about the conflicts since he did the manual approval feature and we'll get it resolved soon. Thanks for the feedback!

**Comment by nitinankad** [comment]
Managed to get it fixed, everything should be deployed and up to date now. Going to close this issue. Thanks again for letting me know!
